### PR TITLE
Introduce --exclude-strip option

### LINKED ISSUE #5: perl stripping filter
hi

i would like to perl strip only selected modules (files). in fact i want  to strip all external modules, except files from my own package. (strip: `local`, no-strip: `lib`)

the reason i don't want to strip my own modules is that it makes very hard to debug problems by me or end users if the code is minified to single line.

### PR DESCRIPTION
**Pull request by skaji**
fix #5 

This PR introduces `--exclude-strip` option. Eg:

``` bash
# when you want to keep pod in your MyApp modules
$ fatpack-simple --exclude-strip 'MyApp.*.pm' script.pl

# when some cpan module does not work well with Perl::Strip
$ fatpack-simple --exclude-strip 'Pod/Simple/BlackBox.pm' script.pl
```

### CODE REVIEW

**Comment by glensc** [comment]
seems it takes pattern not from start of the root, but any path component, thus resulting `local/lib` being excluded, while i wanted to exclude `lib/*`:

```
fatpack-simple \
    --exclude-strip='lib/*' \
    --exclude-strip='bin/*' \
    --exclude=Module::Build,CPAN::Meta,Module::CPANfile \
    bin/check_raid.pl --output ../check_raid.pl
-> fatpack App/Monitoring/Plugin/CheckRaid.pm (without perl-strip)
...
-> fatpack Dist/CheckConflicts.pm (without perl-strip)
```

```
$ find -name CheckRaid.pm -o -name CheckConflicts.pm
./local/lib/perl5/Dist/CheckConflicts.pm
./lib/App/Monitoring/Plugin/CheckRaid.pm
```

**Comment by skaji** [comment]
@glensc Thank you for your tesitng! Please try `--exclude-strip '^lib/'`.

**Comment by glensc** [comment]
ah, thanks, anchor works!

so LGTM for merge

**Comment by glensc** [comment]
i hope you make release too, so i could start using the new option!

**Comment by skaji** [comment]
@glensc Released https://metacpan.org/release/SKAJI/App-FatPacker-Simple-0.07

**Pull request merged**
